version: '3'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
        - health-check
        - authentication
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80

  health-check:
    image: health-check
    container_name: health-check
    build:
      context: ./health-check
    ports:
      - 8080:80
    restart: on-failure

  authentication:
    image: authentication
    container_name: authentication
    build:
      context: ./auth
    ports:
      - 5001:5001
    restart: on-failure